### ISSUE TITLE
scoped causing deprecation warnings in Rails 4

### ISSUE THREAD

**Issue by hkroger** [desktoppr/cached_counts#3]
We get a lot of this when running tests with cached_counts:
DEPRECATION WARNING: Model.scoped is deprecated. Please use Model.all instead.

lib/cached_counts/active_record_base_methods.rb row 14 seems to contain that "scoped" that the warning is referring to.

**Comment by hkroger** [comment]
Actually it seems to be fixed, but it's not yet in the latest gem. Could you publish an update?

**Comment by mariovisic** [comment]
Sure, 0.2.5 has the fix, https://rubygems.org/gems/cached_counts
